### ISSUE TITLE
Poor matches Groningen

### ISSUE THREAD

**Issue by pelderson** [fwsmit/osm-knooppunten#1]
Dataset Groningen Poor matches bekeken. Deze bevat twee knooppunten. De ene (57) is goed: hij staat in de buurt van een wandelknooppunt 57 in OSM. De afstand ertussen is voor knooppunten niet ongewoon. 

De tweede (1) bestaat in OSM helemaal niet als wandelknoopppunt. Het enige punt in de buurt in OSM is een fietsknooppunt met een heel ander nummer! Deze had denk ik helemaal niet in de dataset van Routedatabank moeten zitten. Of.. ja, misschien is dit een voorbeeld van een nieuw knooppunt? Maar dan had het een non-match moeten zijn toch?

**Comment by fwsmit** [comment]
Met deze fix is er wel veel veranderd in de verdeling van knooppunten:

Voor de fix:
Nodes analyzed (external): 1386
Nodes analyzed (OSM): 1386
Great matches (<1m): 1376
Good matches: (1-10m): 4
Poor matches: (10-100m): 2
Non matches: (>100m)): 4

Na de fix:
Nodes analyzed (external): 1386
Nodes analyzed (OSM): 1386
Great matches (<1m): 583
Good matches: (1-10m): 729
Poor matches: (10-100m): 60
Non matches: (>100m)): 14

**Comment by pelderson** [comment]
Ok! Dat maakt sens. Kan je voor mij (ikke blont) nog kort zeggen wat er in elk bestand precies zit? 
Ik denk in termen van Query's op een relationele database, dus zoiets:
Bestand X: Geef lokatie en knooppuntnummer van de Netwerk nodes in Groningen die in Routedatabank zitten EN met hetzelfde nummer ook binnen een afstand van ca ... meter in OSM staan. 
Bestand Z: Lokatie en nummer van de Netwerk nodes in Groningen die in OSM zitten MAAR NIET met hetzelfde nummer binnen ... meter in de Routedatabank staan.

Want je hebt per nauwkeurigheidsniveau toch 3 bestanden: a. OSM en RB gelijk; b. Wel in OSM maar niet in RB; c. Wel in RB maar niet in OSM, of zit het nog anders?

**Comment by pelderson** [comment]
Ik heb om te beginnen de non-matches bekeken. 
Daar zitten echte toevoegingen tussen: dat is goed. 
Er zitten ook verplaatsingen in, dwz wegens een routewijziging is het knooppunt > 100m verplaatst. Daar moet je als mapper wel op bedacht zijn en het zorgvuldig natrekken, maar als signaal is het prima.
Er zitten ook punten in zonder nummer. Ik zou het handig vinden als die er apart als "fouten" uitgefilterd waren, in een "foute punten"-bestandje. Dat zijn namelijk geplande maar niet gerealiseerde punten, zonder nummer of met nummer 0 of soms zelfs ?. Maar dat is dan voor later denk ik. Ook hier: je moet erop bedacht zijn, als mapper.

Ik ben geen non-matches tegengekomen die eigenlijk gewoon matches zijn maar toevallig vrij ver van elkaar staan. Bij het analyseren van fietsknooppunten verwacht ik dat geregeld wel tegen te komen.

Wat duidelijk is, is dat je dit nooit automatisch kan toevoegen. Je moet de situatie beoordelen, kijken wat er aan de hand is, besluiten of er survey nodig is; het punt op de juiste wegkruising zetten, soms routes splitsen, routes verleggen, verlengen en inkorten, soms volgordes omdraaien...

Als je omgekeerd kijkt wat er in OSM zit zonder match in Routedatabank, dan ga je echte verwijderingen zien, maar ook verre verplaatsingen die ook al in deze non-matches te vinden waren.

**Comment by fwsmit** [comment]
> Ik heb om te beginnen de non-matches bekeken. 
> Daar zitten echte toevoegingen tussen: dat is goed. 
> Er zitten ook verplaatsingen in, dwz wegens een routewijziging is het knooppunt > 100m verplaatst. Daar moet je als mapper wel op bedacht zijn en het zorgvuldig natrekken, maar als signaal is het prima.

Als ik meerdere versies van de routedatabank data heb dan kan ik ook expliciet zoeken voor verplaatsingen. 

> Er zitten ook punten in zonder nummer. Ik zou het handig vinden als die er apart als "fouten" uitgefilterd waren, in een "foute punten"-bestandje. Dat zijn namelijk geplande maar niet gerealiseerde punten, zonder nummer of met nummer 0 of soms zelfs ?. Maar dat is dan voor later denk ik. Ook hier: je moet erop bedacht zijn, als mapper.

Dit is prima te doen. Ik zal het binnenkort toevoegen. Zou je hier een issue over kunnen aanmaken? 

> Ik ben geen non-matches tegengekomen die eigenlijk gewoon matches zijn maar toevallig vrij ver van elkaar staan. Bij het analyseren van fietsknooppunten verwacht ik dat geregeld wel tegen te komen.
> 
> Wat duidelijk is, is dat je dit nooit automatisch kan toevoegen. Je moet de situatie beoordelen, kijken wat er aan de hand is, besluiten of er survey nodig is; het punt op de juiste wegkruising zetten, soms routes splitsen, routes verleggen, verlengen en inkorten, soms volgordes omdraaien...

Ja ik was ook niet van plan om het volledig te automatiseren. Wel kunnen zo veel mogelijk handmatig werk te verminderen. 

> Als je omgekeerd kijkt wat er in OSM zit zonder match in Routedatabank, dan ga je echte verwijderingen zien, maar ook verre verplaatsingen die ook al in deze non-matches te vinden waren. 

Die kun je zien in osm_match_0.geojson. Het zijn er maar 14

**Comment by pelderson** [comment]
> > Als je omgekeerd kijkt wat er in OSM zit zonder match in Routedatabank, dan ga je echte verwijderingen zien, maar ook verre verplaatsingen die ook al in deze non-matches te vinden waren.
> 
> Die kun je zien in osm_match_0.geojson. Het zijn er maar 14

Hee, dat bestand zie ik niet!
14 verwijderingen in Groningen vind ik best veel trouwens! Zoals gezegd, daar zitten ook verplaatsingen > 100 meter bij, meestal zijn dat forse ingrepen in het netwerk bijvoorbeeld omdat er een weg, pad, brug of veerpont niet meer gebruikt kan worden.

**Comment by fwsmit** [comment]
Oeps, die was ik vergeten te exporteren. Het script exporteert ze nu wel. Alleen de nodes met precies 1 match vond ik niet nodig om te exporteren.

Ze zullen niet allemaal weg hoeven inderdaad. Uit een snelle test blijkt dat dit de gevonden afstanden zijn:
Distance:  3210.0528970990886
Distance:  14918.15050527517
Distance:  1512.242458025517
Distance:  653.2220857045949
Distance:  380.64847720089597
Distance:  3307.994895619801
Distance:  13440.421219252528
Distance:  7722.456504139316
Distance:  136.46894663501837
Distance:  886.9171110587592

Ik zal ook wel proberen de afstanden toe te voegen aan de geojson export

**Comment by fwsmit** [comment]
De afstand van de dischtbijzijnde node wordt nu ook naar geojson geexporteerd.
