### ISSUE TITLE
Knooppunten zonder nummer of met de waarde 0 of ?

### ISSUE THREAD

**Issue by pelderson** [fwsmit/osm-knooppunten#2]
Ik zou het handig vinden als punten zonder nummer of een niet-bestaanbaar nummer zoals ? en 0 in een apart "foute punten"-bestandje staan. Dat zijn namelijk meestal geplande maar niet gerealiseerde punten, zonder nummer of met nummer 0 of soms zelfs ?.

**Comment by fwsmit** [comment]
Gefixt. In de routedatabank dataset heb ik in de regio groningen alleen knooppunten gevonden met het nummer "", maar de detectie zou ook moeten werken voor andere fouten.

De foutieve knooppunten worden uitgesplitst en worden ook niet gebruikt voor de vergelijking met OSM.

**Comment by fwsmit** [comment]
Oh, die worden dan wel een probleem. Ik zal er wel een issue van aanmaken.

**Comment by pelderson** [comment]
> Oh, die worden dan wel een probleem. Ik zal er wel een issue van aanmaken.

Haha, als de basis werkt dan begint het altijd pas! Het zal een stringvergelijking moeten worden ipv numeriek. 

(Stel dat de Fransen en de Duitsers dit ook willen gebruiken dan heb je nog een extra probleem met de Knooppunten die een naam hebben ipv een nummer of een nummercode. Ik weet dat zij daarvoor heel graag officiële datasets zouden gebruiken en ze mogen dat ook.  Maar dat is van later zorg.)

**Comment by fwsmit** [comment]
Het zal niet zo'n groot probleem zijn verwacht ik. Het is alleen een kwestie van testen en edge cases vinden. Maar gelukkig weet jij wat voor edge cases er bestaan. Python is verder heel flexibel met datatypes.
