### ISSUE TITLE
groningen is hardcoded

### ISSUE THREAD

**Issue by richardbrinkman** [fwsmit/osm-knooppunten#7]
Momenteel is groningen hardcoded in de source code. Mooier zou zijn als je de bestandsnamen als `groningen.osm`, `Wandelknooppunten (wgs84).geojson` en de `filter_regio` als commandline parameters zou kunnen specificeren. Bijvoorbeeld:

```
python3 knooppunten.py --osmfile groningen.osm --importfile "Wandelknooppunten (wgs84).geojson" --region Groningen
```

**Comment by fwsmit** [comment]
Dit is nu geïmplementeerd.
