### ISSUE TITLE
verduidelijk genereren input data

### ISSUE THREAD

**Issue by richardbrinkman** [fwsmit/osm-knooppunten#8]
In de Readme staat iets over de Data Sources, maar dit is onvoldoende om bestanden als `groningen.osm` en `Wandelknooppunten (wgs84).geojson' te kunnen maken.

`groningen.osm` bevat alleen knooppunten. Je script gaat er ook vanuit dat dit alleen knooppunten bevat, aangezien alle nodes worden toegevoegd aan in de `OSMContentHandler` onafhankelijk of hier een `rwn_ref` of `rcn_ref` op staat. Waarschijnlijk heb je dus iets slims gedaan in JOSM om enkel die te exporteren. Je zou ook je script zodanig aan kunnen passen dat hij zelf het osm bestand download m.b.v. een Overpass query.

`Wandelknooppunten (wgs84).geojson` is nog onduidelijker hoe je die kunt maken. Ik neem aan dat je ergens op knooppuntnet.nl iets moet downloaden o.i.d., maar ik zie daar nergens een export functie. De link https://docs.qgis.org/2.18/en/docs/training_manual/online_resources/wfs.html maakt ook niet duidelijk waar ik de knooppunten van Knooppuntnet kan downloaden.

**Comment by fwsmit** [comment]
Ik zal wel wat verduidelijken over hoe de datasets zijn gemaakt.

@pelderson kan jij vertellen hoe je de data van de routedatabank hebt gekregen? Kunnen wij dat ook doen?

**Comment by fwsmit** [comment]
Ik heb in de README verduidelijkt hoe ik aan de data kom. De routedatabank data kan je alleen downloaden met account, dus heb ik verder niet over uitgeweid.
